use crate::PluginHttpMethod;

pub(super) const CORE_ENDPOINTS: &[(PluginHttpMethod, &str)] = &[
    (PluginHttpMethod::Post, "/sign-in/social"),
    (PluginHttpMethod::Get, "/callback/:id"),
    (PluginHttpMethod::Post, "/callback/:id"),
    (PluginHttpMethod::Get, "/get-session"),
    (PluginHttpMethod::Post, "/get-session"),
    (PluginHttpMethod::Post, "/sign-out"),
    (PluginHttpMethod::Post, "/sign-up/email"),
    (PluginHttpMethod::Post, "/sign-in/email"),
    (PluginHttpMethod::Post, "/reset-password"),
    (PluginHttpMethod::Post, "/verify-password"),
    (PluginHttpMethod::Get, "/verify-email"),
    (PluginHttpMethod::Post, "/send-verification-email"),
    (PluginHttpMethod::Post, "/change-email"),
    (PluginHttpMethod::Post, "/change-password"),
    (PluginHttpMethod::Post, "/update-session"),
    (PluginHttpMethod::Post, "/update-user"),
    (PluginHttpMethod::Post, "/delete-user"),
    (PluginHttpMethod::Post, "/request-password-reset"),
    (PluginHttpMethod::Get, "/reset-password/:token"),
    (PluginHttpMethod::Get, "/list-sessions"),
    (PluginHttpMethod::Post, "/revoke-session"),
    (PluginHttpMethod::Post, "/revoke-sessions"),
    (PluginHttpMethod::Post, "/revoke-other-sessions"),
    (PluginHttpMethod::Post, "/link-social"),
    (PluginHttpMethod::Get, "/list-accounts"),
    (PluginHttpMethod::Get, "/delete-user/callback"),
    (PluginHttpMethod::Post, "/unlink-account"),
    (PluginHttpMethod::Post, "/refresh-token"),
    (PluginHttpMethod::Post, "/get-access-token"),
    (PluginHttpMethod::Get, "/account-info"),
    (PluginHttpMethod::Get, "/ok"),
    (PluginHttpMethod::Get, "/error"),
];
