use crate::PluginHttpMethod;

pub(super) const CORE_ENDPOINTS: &[(PluginHttpMethod, &str, &str)] = &[
    (PluginHttpMethod::Post, "/sign-in/social", "socialSignIn"),
    (
        PluginHttpMethod::Get,
        "/callback/:id",
        "handleOAuthCallback",
    ),
    (
        PluginHttpMethod::Post,
        "/callback/:id",
        "handleOAuthCallback",
    ),
    (PluginHttpMethod::Get, "/get-session", "getSession"),
    (PluginHttpMethod::Post, "/get-session", "getSession"),
    (PluginHttpMethod::Post, "/sign-out", "signOut"),
    (
        PluginHttpMethod::Post,
        "/sign-up/email",
        "signUpWithEmailAndPassword",
    ),
    (PluginHttpMethod::Post, "/sign-in/email", "signInEmail"),
    (PluginHttpMethod::Post, "/reset-password", "resetPassword"),
    (PluginHttpMethod::Post, "/verify-password", "verifyPassword"),
    (PluginHttpMethod::Get, "/verify-email", "verifyEmail"),
    (
        PluginHttpMethod::Post,
        "/send-verification-email",
        "sendVerificationEmail",
    ),
    (PluginHttpMethod::Post, "/change-email", "changeEmail"),
    (PluginHttpMethod::Post, "/change-password", "changePassword"),
    (PluginHttpMethod::Post, "/update-session", "updateSession"),
    (PluginHttpMethod::Post, "/update-user", "updateUser"),
    (PluginHttpMethod::Post, "/delete-user", "deleteUser"),
    (
        PluginHttpMethod::Post,
        "/request-password-reset",
        "requestPasswordReset",
    ),
    (
        PluginHttpMethod::Get,
        "/reset-password/:token",
        "resetPasswordCallback",
    ),
    (PluginHttpMethod::Get, "/list-sessions", "listUserSessions"),
    (PluginHttpMethod::Post, "/revoke-session", "revokeSession"),
    (PluginHttpMethod::Post, "/revoke-sessions", "revokeSessions"),
    (
        PluginHttpMethod::Post,
        "/revoke-other-sessions",
        "revokeOtherSessions",
    ),
    (PluginHttpMethod::Post, "/link-social", "linkSocialAccount"),
    (PluginHttpMethod::Get, "/list-accounts", "listUserAccounts"),
    (
        PluginHttpMethod::Get,
        "/delete-user/callback",
        "deleteUserCallback",
    ),
    (PluginHttpMethod::Post, "/unlink-account", "unlinkAccount"),
    (PluginHttpMethod::Post, "/refresh-token", "refreshToken"),
    (
        PluginHttpMethod::Post,
        "/get-access-token",
        "getAccessToken",
    ),
    (PluginHttpMethod::Get, "/account-info", "accountInfo"),
    (PluginHttpMethod::Get, "/ok", "ok"),
    (PluginHttpMethod::Get, "/error", "error"),
];
