//! Native interpreter for schemas generated by `@polar-sh/sdk@0.47.1`.
//!
//! Regenerate the checked-in catalog with
//! `node conformance/generate-polar-schema.mjs` after intentionally changing the pinned SDK.

mod catalog;
mod engine;
mod error;

use serde_json::Value;

pub(crate) use error::SchemaError;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ComponentKind {
    Checkout,
    Customer,
    CustomerSession,
    CustomerState,
    CustomerPage,
    BenefitGrantPage,
    CustomerSubscriptionPage,
    OrderPage,
    MeterPage,
    SubscriptionPage,
    Ingestion,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum OutboundKind {
    CheckoutCreate,
    CustomerCreate,
    CustomerUpdate,
    CustomerUpdateExternal,
    EventsIngest,
    CustomerSessionCreate,
    CustomersList,
    BenefitGrantsList,
    CustomerSubscriptionsList,
    CustomerOrdersList,
    CustomerMetersList,
    SubscriptionsList,
}

impl OutboundKind {
    const fn root(self) -> &'static str {
        match self {
            Self::CheckoutCreate => "outbound:checkoutCreate",
            Self::CustomerCreate => "outbound:customerCreate",
            Self::CustomerUpdate => "outbound:customerUpdate",
            Self::CustomerUpdateExternal => "outbound:customerUpdateExternal",
            Self::EventsIngest => "outbound:eventsIngest",
            Self::CustomerSessionCreate => "outbound:customerSessionCreate",
            Self::CustomersList => "outbound:customersList",
            Self::BenefitGrantsList => "outbound:benefitGrantsList",
            Self::CustomerSubscriptionsList => "outbound:customerSubscriptionsList",
            Self::CustomerOrdersList => "outbound:customerOrdersList",
            Self::CustomerMetersList => "outbound:customerMetersList",
            Self::SubscriptionsList => "outbound:subscriptionsList",
        }
    }
}

impl ComponentKind {
    const fn root(self) -> &'static str {
        match self {
            Self::Checkout => "checkout",
            Self::Customer => "customer",
            Self::CustomerSession => "customerSession",
            Self::CustomerState => "customerState",
            Self::CustomerPage => "customerPage",
            Self::BenefitGrantPage => "benefitGrantPage",
            Self::CustomerSubscriptionPage => "customerSubscriptionPage",
            Self::OrderPage => "orderPage",
            Self::MeterPage => "meterPage",
            Self::SubscriptionPage => "subscriptionPage",
            Self::Ingestion => "ingestion",
        }
    }
}

pub(crate) fn normalize_component(value: Value, kind: ComponentKind) -> Result<Value, SchemaError> {
    engine::normalize_root(value, kind.root())
}

/// Validate and project an already serialized Polar request wire object.
pub(crate) fn normalize_outbound(value: Value, kind: OutboundKind) -> Result<Value, SchemaError> {
    engine::normalize_root(value, kind.root())
}

pub(crate) fn normalize_webhook(value: Value) -> Result<(String, Value), SchemaError> {
    let event_type = value
        .get("type")
        .and_then(Value::as_str)
        .ok_or_else(|| SchemaError::new("$.type", "a recognized webhook event type"))?
        .to_owned();
    let root = format!("webhook:{event_type}");
    engine::normalize_root(value, &root).map(|value| (event_type, value))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn rejects_incomplete_sdk_objects_and_strips_unknown_fields_recursively() {
        assert!(normalize_component(json!({"id":"customer_1"}), ComponentKind::Customer).is_err());
        let customer = json!({
            "id": "customer_1",
            "created_at": "2025-01-01T01:02:03.4567+01:00",
            "modified_at": null,
            "metadata": {"dynamic_key": "kept"},
            "email": "person@example.com",
            "email_verified": true,
            "type": "individual",
            "name": null,
            "billing_address": {
                "line1": "1 Main Street",
                "country": "GB",
                "provider_only": true
            },
            "tax_id": null,
            "organization_id": "organization_1",
            "deleted_at": null,
            "avatar_url": "https://example.test/avatar",
            "provider_only": true
        });
        let normalized = normalize_component(customer, ComponentKind::Customer).unwrap();
        assert_eq!(normalized["createdAt"], "2025-01-01T00:02:03.456Z");
        assert!(normalized.get("providerOnly").is_none());
        assert!(normalized["billingAddress"].get("providerOnly").is_none());
        assert_eq!(normalized["metadata"]["dynamic_key"], "kept");
    }

    #[test]
    fn validates_full_webhook_root_and_allows_open_enums() {
        let invalid = json!({
            "type": "customer.created",
            "timestamp": "2025-01-01T00:00:00Z",
            "data": {"id": "customer_1"}
        });
        assert!(normalize_webhook(invalid).is_err());

        let unknown = json!({"type":"future.event","timestamp":"2025-01-01T00:00:00Z","data":{}});
        assert!(normalize_webhook(unknown).is_err());
    }

    #[test]
    fn applies_sdk_safe_integer_and_javascript_number_rules() {
        let value = json!(9_007_199_254_740_992_u64);
        let error = engine::normalize_root(value, "ingestion").unwrap_err();
        assert!(error.to_string().contains("expected an object"));
        assert_eq!(
            engine::normalize_root(json!({"inserted": 1.0}), "ingestion").unwrap()["inserted"],
            1
        );
    }

    #[test]
    fn validates_and_defaults_pinned_outbound_wire_models() {
        assert_eq!(
            normalize_outbound(
                json!({"email":"person@example.com","name":null,"type":"individual"}),
                OutboundKind::CustomerCreate,
            )
            .unwrap(),
            json!({"email":"person@example.com","name":null,"type":"individual"})
        );
        assert_eq!(
            normalize_outbound(
                json!({"email":"person@example.com"}),
                OutboundKind::CustomersList
            )
            .unwrap(),
            json!({"email":"person@example.com","page":1,"limit":10})
        );
        assert!(normalize_outbound(json!({"events":"wrong"}), OutboundKind::EventsIngest).is_err());
    }
}
