use serde_json::Value;

const RESERVED: &[&str] = &[
    "client_id",
    "client_secret",
    "client_secret_expires_at",
    "client_id_issued_at",
    "scope",
    "user_id",
    "client_name",
    "client_uri",
    "logo_uri",
    "contacts",
    "tos_uri",
    "policy_uri",
    "jwks",
    "jwks_uri",
    "software_id",
    "software_version",
    "software_statement",
    "redirect_uris",
    "post_logout_redirect_uris",
    "backchannel_logout_uri",
    "backchannel_logout_session_required",
    "token_endpoint_auth_method",
    "grant_types",
    "response_types",
    "application_type",
    "disabled",
    "skip_consent",
    "enable_end_session",
    "require_pkce",
    "dpop_bound_access_tokens",
    "subject_type",
    "reference_id",
    "public",
    "type",
    "resources",
    "client_credentials_scopes",
    "clientId",
    "clientSecret",
    "clientDiscoveryId",
    "userId",
    "createdAt",
    "updatedAt",
    "expiresAt",
    "name",
    "uri",
    "icon",
    "tos",
    "policy",
    "softwareId",
    "softwareVersion",
    "softwareStatement",
    "redirectUris",
    "postLogoutRedirectUris",
    "backchannelLogoutUri",
    "backchannelLogoutSessionRequired",
    "tokenEndpointAuthMethod",
    "grantTypes",
    "responseTypes",
    "applicationType",
    "jwksUri",
    "skipConsent",
    "enableEndSession",
    "requirePKCE",
    "dpopBoundAccessTokens",
    "subjectType",
    "referenceId",
    "metadata",
];

pub(super) fn sanitize(metadata: &mut Option<Value>) {
    if let Some(Value::Object(values)) = metadata {
        values.retain(|name, _| !RESERVED.contains(&name.as_str()));
        if values.is_empty() {
            *metadata = None;
        }
    }
}
