use super::*;
use crate::{
    AdapterSchemaOptions, AdditionalFieldReference, AuthConfig, AuthSchemaCatalog,
    DatabaseIdGeneration, PluginSchemaTable,
};
use std::sync::Arc;

fn resolved(strategy: DatabaseIdGeneration) -> ResolvedAdapterSchema {
    let mut config = AuthConfig::new([18; 32]).unwrap();
    config.database_id_generation = strategy;
    config.user.model_name = Some("people".into());
    let tables = vec![
        PluginSchemaTable::new("parent"),
        PluginSchemaTable::new("child")
            .field(
                "parentId",
                AdditionalField::new(AdditionalFieldType::String).references(
                    AdditionalFieldReference {
                        model: "parent".into(),
                        field: "id".into(),
                        on_delete: None,
                    },
                ),
            )
            .field(
                "userId",
                AdditionalField::new(AdditionalFieldType::String).references(
                    AdditionalFieldReference {
                        model: "user".into(),
                        field: "id".into(),
                        on_delete: None,
                    },
                ),
            ),
    ];
    ResolvedAdapterSchema::new(
        Arc::new(AuthSchemaCatalog::build(&config, tables).unwrap()),
        AdapterSchemaOptions::default(),
    )
    .unwrap()
}

#[test]
fn default_database_and_callback_storage_use_text_ids_without_defaults() {
    for strategy in [
        DatabaseIdGeneration::Default,
        DatabaseIdGeneration::Database,
    ] {
        let schema = resolved(strategy);
        let physical = PostgresPhysicalSchema::new(&schema).unwrap();
        let sql = physical.migration_sql(&schema).unwrap();
        assert!(sql.contains("CREATE TABLE \"parent\" (\n  \"id\" TEXT PRIMARY KEY"));
        assert!(sql.contains("\"parentId\" TEXT NOT NULL REFERENCES \"parent\"(\"id\")"));
        assert!(sql.contains("\"userId\" TEXT NOT NULL REFERENCES \"people\"(\"id\")"));
        assert!(!sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
        assert!(!sql.contains("gen_random_uuid"));

        let child = physical.model("child").unwrap();
        assert!(matches!(
            child.encode("id", serde_json::json!("child-1")).unwrap(),
            PostgresValue::Text(Some(value)) if value == "child-1"
        ));
        assert!(matches!(
            child
                .encode("parentId", serde_json::json!("parent-1"))
                .unwrap(),
            PostgresValue::Text(Some(value)) if value == "parent-1"
        ));
    }
}

#[test]
fn serial_storage_uses_identity_integer_ids_and_integer_references() {
    let schema = resolved(DatabaseIdGeneration::Serial);
    let physical = PostgresPhysicalSchema::new(&schema).unwrap();
    let sql = physical.migration_sql(&schema).unwrap();
    assert!(sql.contains(
        "CREATE TABLE \"parent\" (\n  \"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    ));
    assert!(sql.contains("\"parentId\" INTEGER NOT NULL REFERENCES \"parent\"(\"id\")"));
    assert!(sql.contains("\"userId\" INTEGER NOT NULL REFERENCES \"people\"(\"id\")"));

    let objects = physical.schema_objects(&schema);
    assert!(objects.iter().any(|object| matches!(
        object,
        super::super::schema::PostgresSchemaObject::Column { table, name, data_type }
            if table == "child" && name == "id" && data_type == "integer"
    )));
    let child = physical.model("child").unwrap();
    assert!(matches!(
        child.encode("id", serde_json::json!("42")).unwrap(),
        PostgresValue::Integer(Some(42))
    ));
    assert!(matches!(
        child
            .encode("parentId", serde_json::json!(" 0x7 "))
            .unwrap(),
        PostgresValue::Integer(Some(7))
    ));
}

#[test]
fn uuid_storage_uses_native_uuid_defaults_and_uuid_references() {
    let schema = resolved(DatabaseIdGeneration::Uuid);
    let physical = PostgresPhysicalSchema::new(&schema).unwrap();
    let sql = physical.migration_sql(&schema).unwrap();
    assert!(sql.contains(
        "CREATE TABLE \"parent\" (\n  \"id\" UUID DEFAULT pg_catalog.gen_random_uuid() PRIMARY KEY"
    ));
    assert!(sql.contains("\"parentId\" UUID NOT NULL REFERENCES \"parent\"(\"id\")"));
    assert!(sql.contains("\"userId\" UUID NOT NULL REFERENCES \"people\"(\"id\")"));

    let child = physical.model("child").unwrap();
    assert!(matches!(
        child
            .encode("id", serde_json::json!(uuid::Uuid::nil().to_string()))
            .unwrap(),
        PostgresValue::Uuid(Some(value)) if value == uuid::Uuid::nil()
    ));
}
