use super::{
    CUSTOMER_FIELD, ITEM_TABLE, ORGANIZATION_CUSTOMER_COLUMN, ORGANIZATION_TABLE,
    SUBSCRIPTION_TABLE,
};

pub(super) fn render(subscriptions_enabled: bool, organization_enabled: bool) -> String {
    let mut sql = customer_schema(organization_enabled);
    if subscriptions_enabled {
        sql.push_str(&subscription_schema());
    }
    sql
}

fn customer_schema(organization_enabled: bool) -> String {
    if organization_enabled {
        format!(
            "ALTER TABLE IF EXISTS {ORGANIZATION_TABLE} \
             ADD COLUMN IF NOT EXISTS {ORGANIZATION_CUSTOMER_COLUMN} TEXT;\n\
             CREATE UNIQUE INDEX IF NOT EXISTS \
             lucid_auth_chargebee_organization_customer_uidx \
             ON {ORGANIZATION_TABLE} ({ORGANIZATION_CUSTOMER_COLUMN}) \
             WHERE {ORGANIZATION_CUSTOMER_COLUMN} IS NOT NULL;\n"
        )
    } else {
        format!(
            "CREATE UNIQUE INDEX IF NOT EXISTS lucid_auth_chargebee_user_customer_uidx \
             ON lucid_auth_users ((additional_fields ->> '{CUSTOMER_FIELD}')) \
             WHERE (additional_fields ->> '{CUSTOMER_FIELD}') IS NOT NULL;\n"
        )
    }
}

fn subscription_schema() -> String {
    format!(
        "CREATE TABLE IF NOT EXISTS {SUBSCRIPTION_TABLE} (\n\
             id UUID PRIMARY KEY,\n\
             reference_id TEXT NOT NULL,\n\
             chargebee_customer_id TEXT,\n\
             chargebee_subscription_id TEXT,\n\
             status TEXT NOT NULL DEFAULT 'future',\n\
             period_start TIMESTAMPTZ,\n\
             period_end TIMESTAMPTZ,\n\
             trial_start TIMESTAMPTZ,\n\
             trial_end TIMESTAMPTZ,\n\
             canceled_at TIMESTAMPTZ,\n\
             seats DOUBLE PRECISION,\n\
             metadata TEXT,\n\
             created_at TIMESTAMPTZ NOT NULL,\n\
             updated_at TIMESTAMPTZ NOT NULL\n\
         );\n\
         CREATE INDEX IF NOT EXISTS lucid_auth_chargebee_subscription_reference_idx \
         ON {SUBSCRIPTION_TABLE} (reference_id);\n\
         CREATE INDEX IF NOT EXISTS lucid_auth_chargebee_subscription_customer_idx \
         ON {SUBSCRIPTION_TABLE} (chargebee_customer_id);\n\
         CREATE UNIQUE INDEX IF NOT EXISTS lucid_auth_chargebee_subscription_provider_uidx \
         ON {SUBSCRIPTION_TABLE} (chargebee_subscription_id) \
         WHERE chargebee_subscription_id IS NOT NULL;\n\
         CREATE TABLE IF NOT EXISTS {ITEM_TABLE} (\n\
             id UUID PRIMARY KEY,\n\
             position BIGINT GENERATED BY DEFAULT AS IDENTITY,\n\
             subscription_id UUID NOT NULL REFERENCES {SUBSCRIPTION_TABLE}(id) ON DELETE CASCADE,\n\
             item_price_id TEXT NOT NULL,\n\
             item_type TEXT NOT NULL,\n\
             quantity DOUBLE PRECISION NOT NULL,\n\
             unit_price DOUBLE PRECISION,\n\
             amount DOUBLE PRECISION\n\
         );\n\
         CREATE INDEX IF NOT EXISTS lucid_auth_chargebee_item_subscription_idx \
         ON {ITEM_TABLE} (subscription_id);\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_only_schema_has_one_unique_json_customer_index() {
        let sql = render(false, false);
        assert!(sql.contains("additional_fields ->> 'chargebeeCustomerId'"));
        assert!(sql.contains("CREATE UNIQUE INDEX"));
        assert!(!sql.contains(ORGANIZATION_CUSTOMER_COLUMN));
        assert!(!sql.contains(SUBSCRIPTION_TABLE));
    }

    #[test]
    fn organization_only_schema_uses_the_organization_column() {
        let sql = render(false, true);
        assert!(sql.contains("ALTER TABLE IF EXISTS lucid_auth_organizations"));
        assert!(sql.contains("chargebee_customer_id TEXT"));
        assert!(!sql.contains("additional_fields"));
        assert!(!sql.contains(SUBSCRIPTION_TABLE));
    }

    #[test]
    fn subscription_schema_keeps_reference_nonunique_and_items_cascading() {
        let sql = render(true, false);
        assert!(sql.contains("reference_id TEXT NOT NULL"));
        assert!(sql.contains("subscription_provider_uidx"));
        assert!(!sql.contains("UNIQUE (reference_id)"));
        assert!(sql.contains("ON DELETE CASCADE"));
        assert!(sql.contains("status TEXT NOT NULL DEFAULT 'future'"));
        assert!(sql.contains("metadata TEXT"));
    }
}
